
trigger:
- main

pool:
  vmImage: ubuntu-latest 


steps:
- task: Docker@2
  inputs:
    containerRegistry: 'DockerHub'
    repository: 'leandroparipe/paymentapiwebapi'
    command: 'buildAndPush'
    Dockerfile: '$(Build.SourcesDirectory)/src/Payment-api.WebAPI/Dockerfile'
    buildContext: '.'
    tags: |
          $(Build.BuildId)
          latest