
trigger:
- main

pool:
  vmImage: ubuntu-latest 


steps:
- task: Docker@2
  inputs:
    containerRegistry: 'DockerHub'
    repository: 'leandroparipe/paymentapiwebapi'
    command: 'buildAndPush'
    Dockerfile: '$(Build.SourcesDirectory)/src/Payment-api.WebAPI/Dockerfile'
    buildContext: '.'
    tags: |
          $(Build.BuildId)
          latest


- task: AzureRmWebAppDeployment@5
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Assinatura 1(a9e610f2-1bae-47a2-a329-aa8f581a2579)'
    appType: 'webAppContainer'
    WebAppName: 'payment-starging'
    DockerNamespace: 'leandroparipe'
    DockerRepository: 'paymentapiwebapi'
    DockerImageTag: '$(Build.BuildId)'