CREATE TABLE IF NOT EXISTS `__EFMigrationsHistory` (
    `MigrationId` varchar(150) CHARACTER SET utf8mb4 NOT NULL,
    `ProductVersion` varchar(32) CHARACTER SET utf8mb4 NOT NULL,
    CONSTRAINT `PK___EFMigrationsHistory` PRIMARY KEY (`MigrationId`)
) CHARACTER SET=utf8mb4;

START TRANSACTION;

ALTER DATABASE CHARACTER SET utf8mb4;

CREATE TABLE `TB_CATEGORIES` (
    `ID_CATEGORY` char(36) COLLATE ascii_general_ci NOT NULL,
    `DESCRIPTION` varchar(100) CHARACTER SET utf8mb4 NOT NULL,
    CONSTRAINT `PK_TB_CATEGORIES` PRIMARY KEY (`ID_CATEGORY`)
) CHARACTER SET=utf8mb4;

CREATE TABLE `TB_ORDERS` (
    `ID_ORDER` char(36) COLLATE ascii_general_ci NOT NULL,
    `DATE` datetime(6) NOT NULL,
    `STATUS` longtext CHARACTER SET utf8mb4 NOT NULL,
    CONSTRAINT `PK_TB_ORDERS` PRIMARY KEY (`ID_ORDER`)
) CHARACTER SET=utf8mb4;

CREATE TABLE `TB_SELLERS` (
    `ID_SELLER` char(36) COLLATE ascii_general_ci NOT NULL,
    `NAME` varchar(400) CHARACTER SET utf8mb4 NOT NULL,
    `DS_EMAIL` varchar(400) CHARACTER SET utf8mb4 NOT NULL,
    `NR_CPF` varchar(20) CHARACTER SET utf8mb4 NOT NULL,
    CONSTRAINT `PK_TB_SELLERS` PRIMARY KEY (`ID_SELLER`)
) CHARACTER SET=utf8mb4;

CREATE TABLE `TB_PRODUCTS` (
    `ID_PRODUCT` char(36) COLLATE ascii_general_ci NOT NULL,
    `DESCRIPTION` varchar(100) CHARACTER SET utf8mb4 NOT NULL,
    `PRICE` decimal(10,2) NOT NULL,
    `CategoryId` char(36) COLLATE ascii_general_ci NOT NULL,
    `ACTIVE` tinyint(1) NOT NULL,
    CONSTRAINT `PK_TB_PRODUCTS` PRIMARY KEY (`ID_PRODUCT`),
    CONSTRAINT `FK_TB_PRODUCTS_TB_CATEGORIES_CategoryId` FOREIGN KEY (`CategoryId`) REFERENCES `TB_CATEGORIES` (`ID_CATEGORY`) ON DELETE CASCADE
) CHARACTER SET=utf8mb4;

CREATE TABLE `TB_PHONES` (
    `ID_PHONE` char(36) COLLATE ascii_general_ci NOT NULL,
    `DDD` varchar(20) CHARACTER SET utf8mb4 NOT NULL,
    `NUMBER` varchar(20) CHARACTER SET utf8mb4 NOT NULL,
    `TYPE` longtext CHARACTER SET utf8mb4 NOT NULL,
    `ID_SELLER` char(36) COLLATE ascii_general_ci NOT NULL,
    CONSTRAINT `PK_TB_PHONES` PRIMARY KEY (`ID_PHONE`),
    CONSTRAINT `FK_TB_PHONES_TB_SELLERS_ID_SELLER` FOREIGN KEY (`ID_SELLER`) REFERENCES `TB_SELLERS` (`ID_SELLER`) ON DELETE CASCADE
) CHARACTER SET=utf8mb4;

CREATE TABLE `TB_SALES` (
    `ID_SALE` char(36) COLLATE ascii_general_ci NOT NULL,
    `MOMENT` datetime(6) NOT NULL,
    `STATUS` longtext CHARACTER SET utf8mb4 NOT NULL,
    `ID_SELLER` char(36) COLLATE ascii_general_ci NOT NULL,
    `ID_ORDER` char(36) COLLATE ascii_general_ci NOT NULL,
    CONSTRAINT `PK_TB_SALES` PRIMARY KEY (`ID_SALE`),
    CONSTRAINT `FK_TB_SALES_TB_ORDERS_ID_ORDER` FOREIGN KEY (`ID_ORDER`) REFERENCES `TB_ORDERS` (`ID_ORDER`) ON DELETE CASCADE,
    CONSTRAINT `FK_TB_SALES_TB_SELLERS_ID_SELLER` FOREIGN KEY (`ID_SELLER`) REFERENCES `TB_SELLERS` (`ID_SELLER`) ON DELETE CASCADE
) CHARACTER SET=utf8mb4;

CREATE TABLE `TB_ORDER_ITEMS` (
    `ID_ORDER_ITEM` char(36) COLLATE ascii_general_ci NOT NULL,
    `ID_ORDER` char(36) COLLATE ascii_general_ci NOT NULL,
    `ID_PRODUCT` char(36) COLLATE ascii_general_ci NOT NULL,
    `DS_PRODUCT` longtext CHARACTER SET utf8mb4 NOT NULL,
    `PRODUCT_UNIT_PRICE` decimal(65,30) NOT NULL,
    `QUANTITY` int NOT NULL,
    CONSTRAINT `PK_TB_ORDER_ITEMS` PRIMARY KEY (`ID_ORDER_ITEM`),
    CONSTRAINT `FK_TB_ORDER_ITEMS_TB_ORDERS_ID_ORDER` FOREIGN KEY (`ID_ORDER`) REFERENCES `TB_ORDERS` (`ID_ORDER`) ON DELETE CASCADE,
    CONSTRAINT `FK_TB_ORDER_ITEMS_TB_PRODUCTS_ID_PRODUCT` FOREIGN KEY (`ID_PRODUCT`) REFERENCES `TB_PRODUCTS` (`ID_PRODUCT`) ON DELETE CASCADE
) CHARACTER SET=utf8mb4;

CREATE UNIQUE INDEX `IX_TB_CATEGORIES_DESCRIPTION` ON `TB_CATEGORIES` (`DESCRIPTION`);

CREATE INDEX `IX_TB_ORDER_ITEMS_ID_ORDER` ON `TB_ORDER_ITEMS` (`ID_ORDER`);

CREATE INDEX `IX_TB_ORDER_ITEMS_ID_PRODUCT` ON `TB_ORDER_ITEMS` (`ID_PRODUCT`);

CREATE INDEX `IX_TB_PHONES_ID_SELLER` ON `TB_PHONES` (`ID_SELLER`);

CREATE INDEX `IX_TB_PRODUCTS_CategoryId` ON `TB_PRODUCTS` (`CategoryId`);

CREATE INDEX `IX_TB_SALES_ID_ORDER` ON `TB_SALES` (`ID_ORDER`);

CREATE INDEX `IX_TB_SALES_ID_SELLER` ON `TB_SALES` (`ID_SELLER`);

CREATE UNIQUE INDEX `IX_TB_SELLERS_NR_CPF` ON `TB_SELLERS` (`NR_CPF`);

INSERT INTO `__EFMigrationsHistory` (`MigrationId`, `ProductVersion`)
VALUES ('20230622000815_AddDatabaseMySQL', '7.0.7');

COMMIT;

